// scripts/assemble-schema.mjs - PLUGIN-MIG-4 schema assembly script.
//
// ADR-024 option D (Hybrid plugin isolation) realization at schema layer.
// Copies packages/tenant-*/prisma/fragment.prisma files to prisma/<tenant-id>.prisma
// so that Prisma 7 multi-file schema (GA v6.7.0+) auto-merges them.
//
// Single source of truth: packages/tenant-<id>/prisma/fragment.prisma
// Build artifact:        prisma/<tenant-id>.prisma (gitignored)
//
// Invocation:
//   - npm run prisma:assemble (manual)
//   - npm run prebuild (auto, before next build)
//
// Why .mjs (ESM Node): avoid tsx/ts-node devDependency.
// Why ASCII-only: avoid Windows console code page encoding mismatch with Node 24 ESM loader.

import {
  readdirSync,
  readFileSync,
  writeFileSync,
  existsSync,
  statSync,
} from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const PACKAGES_DIR = join(REPO_ROOT, "packages");
const PRISMA_DIR = join(REPO_ROOT, "prisma");
const TENANT_PREFIX = "tenant-";

const HEADER = `// AUTO-GENERATED by scripts/assemble-schema.mjs - DO NOT EDIT DIRECTLY.
// Source: packages/{tenant}/prisma/fragment.prisma
// This file is gitignored - regenerated on every build.
// Modify the source fragment and run \`npm run prisma:assemble\`.
`;

function findTenantFragments() {
  if (!existsSync(PACKAGES_DIR)) return [];
  const entries = readdirSync(PACKAGES_DIR);
  const results = [];
  for (const entry of entries) {
    if (!entry.startsWith(TENANT_PREFIX)) continue;
    const fragmentPath = join(PACKAGES_DIR, entry, "prisma", "fragment.prisma");
    if (!existsSync(fragmentPath)) continue;
    if (!statSync(fragmentPath).isFile()) continue;
    const tenantId = entry.slice(TENANT_PREFIX.length);
    results.push({ tenantId, fragmentPath });
  }
  return results;
}

const fragments = findTenantFragments();
if (fragments.length === 0) {
  console.log("[assemble-schema] no tenant fragments found - skip.");
} else {
  for (const { tenantId, fragmentPath } of fragments) {
    const body = readFileSync(fragmentPath, "utf8");
    const destPath = join(PRISMA_DIR, `${tenantId}.prisma`);
    const out = `${HEADER}\n${body}`;
    writeFileSync(destPath, out, "utf8");
    console.log(
      `[assemble-schema] ${tenantId} - ${fragmentPath} -> ${destPath} (${body.length} bytes)`,
    );
  }
  console.log(
    `[assemble-schema] done - ${fragments.length} tenant fragment(s) merged.`,
  );
}
